module "apim_endpoint" {
    source  = "app.terraform.io/exeloncorp/apim-endpoint/azurerm"
    version = "1.0.10"
    tags = var.tags
    operations = var.operations
    apim_instance = var.apim_instance
    identifier = var.identifier
    revision = var.revision
    path_override = var.path_override
    path = var.path
    soap_pass_through = var.soap_pass_through
    wsdl_content_value = var.wsdl_content_value
    wsdl_service_name = var.wsdl_service_name
    wsdl_endpoint_name = var.wsdl_endpoint_name
    service_url_override = var.service_url_override
    service_url = var.service_url
    service_endpoint = var.service_endpoint
    subscription_required = var.subscription_required
    backends = var.backends
    add_product = var.add_product
    named_values = var.named_values
    api_tags = var.api_tags
    policy_override = var.policy_override
    policy_xml_content = var.policy_xml_content
    authorization_server_name = var.authorization_server_name
}